#include "client/ClientSettings.hpp"

#include <fstream>
#include <iostream>

namespace game {

void ClientSettings::load(const std::string& path) {
    Config config;
    if (!config.loadFile(path)) {
        return;
    }

    mouseSensitivity = config.getFloat("client.mouse_sensitivity", mouseSensitivity);
    audioVolume = config.getFloat("client.audio_volume", audioVolume);
    fullscreen = config.getInt("client.fullscreen", fullscreen ? 1 : 0) != 0;
}

void ClientSettings::save(const std::string& path) const {
    std::ofstream file(path, std::ios::trunc);
    if (!file.is_open()) {
        std::cerr << "Failed to open " << path << " for writing\n";
        return;
    }

    file << "# Client configuration\n"
         << "# Generated by game_client\n\n"
         << "client.mouse_sensitivity=" << mouseSensitivity << '\n'
         << "client.audio_volume=" << audioVolume << '\n'
         << "client.fullscreen=" << (fullscreen ? "true" : "false") << '\n';

    if (file.fail()) {
        std::cerr << "Failed to write " << path << '\n';
    }
}

} // namespace game
